### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "dsa@abv.bg",
    "password": "dasdasdas"
}


### Find a a particular user with a given ID
GET http://localhost:3000/auth/2


### Find all users with a given email
GET http://localhost:3000/auth?email=dsa@abv.bg


### Delete a user with a given id
DELETE http://localhost:3000/auth/1

###
PATCH http://localhost:3000/auth/234
Content-Type: application/json

{
    "email": "aaa@aa.com",
    "password": "aaaaa"
}
